config/routes.rb
Rails.application.routes.draw do
  root "tasks#index"

  post "/tasks/:id/toggle", to: "tasks#toggle"

  resources :comments, only: [:create, :update, :destroy]

  resource :session, only: [:new, :create, :destroy]
  get "signin" => "sessions#new"
  get "signout" => "sessions#destroy"

  resources :tasks

  resources :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  has_many :comments, as: :commentable, dependent: :destroy
  belongs_to :commentable, polymorphic: true
  belongs_to :user
end

app/models/image.rb
class Image < ApplicationRecord
  belongs_to :user
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :user
  has_many :comments, as: :commentable, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :tasks, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :images, as: :imageable, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def current_user
    @user ||= User.find(session[:user_id]) if session[:user_id]
  end

  helper_method :current_user
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: %w[ update destroy ]

  def create
    @comment = Comment.new(comment_params)
    @comment.user = User.first # TODO[Jose]: make current_user

    class_name = @comment.commentable.class.to_s
    if class_name == "Comment"
      @comment.origin_id = @comment.commentable.origin_id
      @comment.origin_type = @comment.commentable.origin_type
    elsif class_name == "Task"
      @comment.origin_id = @comment.commentable.id
      @comment.origin_type = class_name
    end

    respond_to do |format|
      if @comment.save
        format.html { redirect_to task_path(@comment.origin_id), notice: "Comment successfully added" }
      else
        format.html { redirect_to task_path(@comment.origin_id), notice: "Comment was not successfully added" }
      end
    end
  end

  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to task_path(@comment.origin_id), notice: "Comment on Task successfully updated" }
      else
        format.html { redirect_to task_path(@comment.origin_id), notice: "Comment was not successfully updated" }
      end
    end
  end

  def destroy
    @comment.destroy
    redirect_to task_path(@comment.origin_id), notice: "Comment successfully deleted"
  end

  private

  def comment_params
    params.require(:comment).permit(:id, :body, :commentable_id, :commentable_type)
  end

  def set_comment
    @comment = Comment.find(params[:id])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(username: params[:username])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_url, notice: "Signed In!"
    else
      flash.now[:alert] = "Invalid email/password combination"
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to signin_path, alert: "Signed Out!"
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: %w[ destroy edit update show toggle ]

  def index
    @tasks = Task.all
    @task = Task.new
  end

  def show
  end

  def create
    @task = Task.new(task_params)
    @task.user = User.first # TODO[Jose]: make current_user

    respond_to do |format|
      if @task.save
        format.html { redirect_to tasks_url, notice: "Task was successfully created" }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  def edit
  end

  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to tasks_path, notice: "Task was successfully updated" }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  def toggle
    @task.update(completed: params[:completed])
    render json: { message: "Task completed" }
  end

  def destroy
    @task.destroy
    redirect_to tasks_path, notice: "Post was successfully deleted"
  end

  private

  def task_params
    params.require(:task).permit(:description)
  end

  def set_task
    @task = Task.find(params[:id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      session[:user_id] = @user.id
      redirect_to tasks_url, notice: "Welcome #{@user.username}!"
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])

    if @user.update(user_params)
      redirect_to @user, notice: "Account Updated!"
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to root_url, status: :see_other, alert: "Account deleted!", confirm: "Are you sure?"
    session[:user_id] = nil
  end

  private

  def user_params
    params.require(:user).permit(:username, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_comment.html.erb
<div data-controller="comments" class="relative grid grid-cols-1 gap-4 p-4 mb-4 border rounded-lg bg-white shadow-sm">
  <div class="flex flex-row">
    <p class="relative whitespace-nowrap truncate overflow-hidden">
      <span class="font-bold text-lg">@<%= comment.user.username %></span>
      said:
      <%= comment.body %>
    </p>
    <a class="text-gray-500 text-xl" href="#"><i class="fa-solid fa-trash"></i></a>

    <div>
      <button data-action="click->comments#showEditCommentForm" class="btn bg-gray-100">Edit</button>
      <div hidden data-comments-target="editCommentForm commentForm">
        <%= render partial: 'comments/form', locals: { path: comment_path(comment), action: :put, comment: comment } %>
      </div>

    </div>

    <div class="inline-block ml-2">
      <%= button_to "Destroy", comment_path(comment), method: :delete, class: "btn bg-red-100" %>
    </div>
  </div>

  <span data-action="click->comments#showNewCommentForm" class="btn bg-gray-100">Add Comment...</span>
  <div hidden data-comments-target="newCommentForm commentForm">
    <%= render partial: 'comments/form', locals: { path: comments_path, action: :post, comment: Comment.new(commentable_id: comment.id, commentable_type: 'Comment' ) } %>
  </div>

  <p class="text-gray-400 text-sm"><%= comment.created_at.to_date %></p>
  <div class="ml-4">
    <p><%= render comment.comments %></p>
  </div>

</div>

app/views/comments/_form.html.erb
<%= form_with(model: comment, method: action, id: "comment-form", class: "mb-7") do |form| %>
  <div class="mb-5">
    <%= form.hidden_field :commentable_id, value: comment.commentable_id %>
    <%= form.hidden_field :commentable_type, value: comment.commentable_type %>
    <%= form.text_field :body, placeholder: "Add new comment", class: "inline-block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-96" %>
    <%= form.submit "Save", class: "btn py-2 ml-2 bg-blue-600 text-white" %>
    <%= button_tag "Cancel", data: { action: "comments#hideCommentForm:prevent" }, class: "btn py-2 ml-2" %>
  </div>
<% end %>

app/views/layouts/_flash.html.erb
<% flash.each do |type, message| %>
  <%= content_tag(:div, message, class: "flash #{type} ") %>
<% end %>

app/views/layouts/_header.html.erb
<nav>
  <% if current_user %>
    <ul>
      <li><%= link_to current_user.username, current_user %></li>
      <li><%= link_to 'Sign Out', signout_path %></li>
    </ul>
  <% else %>
    <ul>
      <li><%= link_to 'Sign In', signin_path %></li>
      <li><%= link_to 'Sign Up', new_user_path %></li>
    </ul>
  <% end %>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GorailsLab</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>

    <%= render 'layouts/header' %>
    <%= render 'layouts/flash' %>

    <main class="container mx-auto mt-28 px-5">
      <%= yield %>
    </main>
  </body>
</html>

app/views/shared/_errors.html.erb
<% if object.errors.any? %>
  <section>
  <h2>
    Oops! Your form could not be saved.
  </h2>
    <h3>
      Please fix the following <%= pluralize(object.errors.size, 'error') %>:
    </h3>
    <ul>
      <% object.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </section>
<% end %>

app/views/tasks/_form.html.erb
<%= form_with(model: task, class: "mb-7") do |form| %>
  <div class="mb-5">
    <%= render 'shared/errors', object: task %>
    <%= form.text_field :description, placeholder: "Add new task", class: "inline-block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-96" %>
    <%= form.submit "Save", class: "btn py-2 ml-2 bg-blue-600 text-white" %>
  </div>
<% end %>

app/views/tasks/_task.html.erb
<div class="block">
  <%= form_with(model: task, class: "text-lg inline-block my-3 w-72") do |form| %>
    <%= form.check_box :completed,
      class: "mr-2 align-middle bg-gray-50 border-gray-300 focus:ring-3 focus:ring-blue-300 h-5 w-5 rounded checked:bg-green-500",
      data: {
        id: task.id,
        action: 'tasks#toggle',
      } %>
    <%= link_to task.description, task %>
  <% end %>

  <%= link_to "Edit", edit_task_path(task), class: "btn bg-gray-100" %>
  <div class="inline-block ml-2">
    <%= button_to "Destroy", task_path(task), method: :delete, class: "btn bg-red-100", data: { action: "tasks#delete" } %>
  </div>
</div>

app/views/tasks/edit.html.erb
<div>
  <h1 class="font-bold text-2xl mb-3">Editing Task</h1>

  <div id="<%= dom_id @task %>">
    <%= render "form", task: @task %>
    <%= link_to "Nevermind", tasks_path, class: "btn mb-3 bg-gray-100" %>
  </div>
</div>

app/views/tasks/index.html.erb
<% if notice.present? %>
  <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice">
    <%= notice %>
  </p>
<% end %>

<h1 class="font-bold text-2xl">Task Manager</h1>

<div class="mt-4">
  <%= render "form", task: @task %>
</div>


<div id="tasks">
  <h1 class="font-bold text-lg mb-7">Tasks</h1>

  <div class="px-5" data-controller="tasks">
    <%= render @tasks %>
  </div>
</div>

app/views/tasks/show.html.erb
<% if notice.present? %>
  <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice">
    <%= notice %>
  </p>
<% end %>


<h3>Task description: <%= @task.description %></h3>

<div class="block">
  <p>leave a comment?</p>
</div>
<div>
<%# TODO[Jose]: fix this, create currnt_user concept %>
    <%= render partial: 'comments/form', locals: { path: comments_path, action: :post, comment: Comment.new(commentable_id: @task.id, commentable_type: 'Task' ) } %>
</div>

<h2>Comments:</h2>
<div>
  <%= render @task.comments %>
</div>

<div>
  <%= link_to 'View All Tasks', tasks_path %>
</div>

app/views/users/_form.html.erb
<%= form_with(model: user) do |f| %>
    <%= render 'shared/errors', object: user %>


  <%= f.label :username %>
  <%= f.text_field :username %>

  <%= f.label :password %>
  <%= f.password_field :password %>

  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation %>

  <% if user.new_record? %>
    <%= f.submit 'Create Account', class: 'btn bg-blue-600 text-white' %>
  <% else %>
    <%= f.submit 'Update Account', class: 'btn bg-blue-600 text-white' %>
  <% end %>
<% end %>

app/views/users/edit.html.erb
<h1>Edit Profile</h1>

<%= render 'form', user: @user %>

app/views/users/new.html.erb
<div>
  <h1 class="font-bold text-4xl">Sign Up</h1>

  <%= render 'form', user: @user %>
</div>

app/views/users/show.html.erb
<h1>Account</h1>


<div>
  <h5><%= @user.username %></h5>

  <%= link_to 'Edit Account', edit_user_path(@user) %>
  <%= button_to 'Delete Account', user_path(@user), method: :delete %>
</div>